### ISSUE TITLE
Sparrow CMake build doesn't find flex or bison

### ISSUE THREAD

**Issue by russel** [Sparrow-lang/sparrow#2]
The build should be able to find the install flex and bison. This is Debian Sid.

|> cmake -DCMAKE_INSTALL_PREFIX=$HOME/Built -DLLVM_DIR=/usr/lib/llvm-3.9 ..
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   program_options
--   timer
-- Boost include: /usr/include
-- LLVM include: /usr/lib/llvm-3.9/include
-- LLVM libs: /usr/lib/llvm-3.9/lib
-- LLVM binaries: /usr/lib/llvm-3.9/bin
-- Could NOT find FLEX (missing:  FLEX_EXECUTABLE) 
-- Could NOT find BISON (missing:  BISON_EXECUTABLE) 
CMake Error at src/SparrowFrontend/CMakeLists.txt:5 (BISON_TARGET):
  Unknown CMake command "BISON_TARGET".

-- Configuring incomplete, errors occurred!
See also "/home/Checkouts/Git/Sparrow/Build_Debian/CMakeFiles/CMakeOutput.log".

|> which flex
/usr/bin/flex

|> which bison
/usr/bin/bison

**Comment by lucteo** [comment]
Hi Russell

Thank you for your interest in Sparrow.

I am already working on fixing this issue. I'm trying to migrate all the components to compile on conan.io. I expect it to be done soon.

To get around this problem, you can pass cmake the paths to Flex & Bison executables and Flex include path. Try something like:
`cmake -D LLVM_DIR=/usr/local/Cellar/llvm/3.5/ -D FLEX_EXECUTABLE=/usr/local/Cellar/flex/2.5.37/bin/ -D FLEX_INCLUDE_DIR=/usr/local/Cellar/flex/2.5.37/include/ -D BISON_EXECUTABLE=/usr/bin/bison ..`

There is another problem with you compilation. LLVM breaks interface between releases, and currently Sparrow only works with LLVM 3.5. I tried to upgrade to LLVM 3.8 these days, but I hit so many problems...

**Comment by lucteo** [comment]
Fixed the compilation of Sparrow on Linux. Tested it on a CentOS 7.2 system.
We now use Conan to be as cross-platform as possible from the build perspective.

Besides compilation errors, there were also some errors in the Sparrow compiler uncovered by moving to a different platform. Most of the problems were solved.

Compilation instructions:
> conan install .. --build=missing
> cmake ..
> cmake --build . -- -j4
optional:
> cmake --build . -- install

After compiling, you can run from the "tests" directory:
> ./test-all
Most of the tests should run correctly.

**Comment by russel** [comment]
Hummm… installed Conan from PyPI. then ran the first step. It downloaded and compiled Boost, bison, bzip2, and flex all of which are installed via Debian packaging to the same version. Not great. zlib also was installed even though zlib1g is installed by Debian packaging. However the worst thing was that LLVM 3.5 was downloaded and installed even though I have 3.6, 3.7, 3.8 and 3.9 already installed because of Debian packaging. This does not give a good feeling 3.5 was ditched by Debian long ago. I would have thought a bleeding edge language would at least be using 3.7 if not 3.8.

CMake line (I add an install prefix) now fine. However on  running make (rather than cmake --build .) I get a mass of errors, the first of which is:
```
  In file included from /usr/include/c++/6/bits/hashtable.h:35:0,
                 from /usr/include/c++/6/unordered_map:47,
                 from /home/Checkouts/Git/Sparrow/src/Nest/../Nest/Utils/DefaultStdInc.hpp:17,
                 from /home/Checkouts/Git/Sparrow/src/Nest/../Nest/src/StdInc.hpp:3,
                 from /home/Checkouts/Git/Sparrow/src/Nest/src/Api/Type.cpp:1:
/usr/include/c++/6/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<Nest_Type, {anonymous}::TypeHasher>’:
/usr/include/c++/6/type_traits:143:12:   required from ‘struct std::__and_<std::__is_fast_hash<{anonymous}::TypeHasher>, std::__detail::__is_noexcept_hash<Nest_Type, {anonymous}::TypeHasher> >’
/usr/include/c++/6/type_traits:154:38:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<{anonymous}::TypeHasher>, std::__detail::__is_noexcept_hash<Nest_Type, {anonymous}::TypeHasher> > >’
/usr/include/c++/6/bits/unordered_set.h:95:63:   required from ‘class std::unordered_set<Nest_Type, {anonymous}::TypeHasher>’
/home/Checkouts/Git/Sparrow/src/Nest/src/Api/Type.cpp:35:37:   required from here
/usr/include/c++/6/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const {anonymous}::TypeHasher) (const Nest_Type&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/Checkouts/Git/Sparrow/src/Nest/src/Api/Type.cpp:28:16: note: candidate: size_t {anonymous}::TypeHasher::operator()(const Type&) <near match>
         size_t operator()(const Type& type)
                ^~~~~~~~
/home/Checkouts/Git/Sparrow/src/Nest/src/Api/Type.cpp:28:16: note:   passing ‘const {anonymous}::TypeHasher*’ as ‘this’ argument discards qualifiers
```

**Comment by lucteo** [comment]
I've seen this error myself yesterday while trying to make a docker with Sparrow. Working on a fix for it.

**Comment by lucteo** [comment]
Hi Russel

Sorry for coming back so late. I fixed some more errors, and I made sure that this compiles with docker on Ubuntu (see lucteo/sparrow-test). Can you please try this again?

Thank you very much,
LucTeo

**Comment by lucteo** [comment]
Closing, as this issue seems to be fixed

**Comment by russel** [comment]
I haven't had chance to try this out yet and won't for a couple of weeks. If I still have problems then I'll reopen.

**Comment by lucteo** [comment]
Thank you very much!
